/* eslint-disable no-debugger */
const reportJson = {
  appname: 'crm',
  blocks: ['appup-report'],
  blockDetails: [{
    block: 'appup-report',
    blockParams: {}
  }
  ],
  templateParams: {
  },
  meta: [{
    id: 628,
    category_id: 98,
    category_name: 'My',
    app_name: 'crm',
    report_type: 'card',
    page_type: 'dashboard',
    title: 'Total Leads',
    title1: 'Total Leads',
    tooltip: '',
    x_axis: '',
    y_axis: '',
    entity: 'contacts',
    field: 'count(id) as count',
    static_filter: '',
    width: 300,
    height: 300,
    xaxis_type: '',
    series_name: '',
    x: 0.0,
    y: 0.0,
    w: 3.0,
    h: 6.2,
    i: 626,
    join_json: '{"where":"is_contacted\u003d0"}',
    table_json: '',
    custom_function: '',
    custom_html: '0'
  }, {
    category_name: 'My',
    app_name: 'crm',
    report_type: 'card',
    page_type: 'dashboard',
    title: 'Converted Leads',
    entity: 'converted_leads',
    field: 'count(id) as count',
    static_filter: '',
    width: 300,
    height: 300,
    xaxis_type: '',
    series_name: '',
    x: 3.0,
    y: 0.0,
    w: 3.0,
    h: 6.2,
    i: 627,
    custom_html: '0'
  }, {
    id: 630,
    category_id: 98,
    category_name: 'My',
    app_name: 'crm',
    report_type: 'card',
    page_type: 'dashboard',
    title: 'Total Contacts',
    title1: 'Total Contacts',
    tooltip: '',
    x_axis: '',
    y_axis: '',
    entity: 'contacts',
    field: 'count(id) as count',
    static_filter: '',
    width: 300,
    height: 300,
    xaxis_type: '',
    series_name: '',
    x: 6.0,
    y: 0.0,
    w: 3.0,
    h: 6.2,
    i: 628,
    join_json: '{"where":"is_contacted\u003d1"}',
    table_json: '',
    custom_function: '',
    custom_html: '0'
  },
  {
    id: 634,
    category_id: 98,
    category_name: 'My',
    app_name: 'crm',
    report_type: 'pie',
    page_type: 'dashboard',
    title: 'Leads by Stages',
    title1: 'Leads by Stages',
    tooltip: '{series.name}: \u003cb\u003e{point.percentage:.1f}%\u003c/b\u003e',
    x_axis: '',
    y_axis: '',
    entity: 'leads_by_stages',
    field: 'lead_stage',
    static_filter: '',
    width: 550,
    height: 330,
    xaxis_type: '',
    series_name: 'stage',
    x: 0.0,
    y: 14.0,
    w: 6.0,
    h: 17.6,
    i: 632,
    join_json: '{}',
    table_json: '',
    custom_function: '',
    custom_html: '0'
  }, {
    id: 635,
    category_id: 98,
    category_name: 'My',
    app_name: 'crm',
    report_type: 'pie',
    page_type: 'dashboard',
    title: 'Contacts by Stages',
    title1: 'Contacts by Stages',
    tooltip: '{series.name}: \u003cb\u003e{point.percentage:.1f}%\u003c/b\u003e',
    x_axis: '',
    y_axis: '',
    entity: 'contacts_by_stages',
    field: 'stage_name',
    static_filter: '',
    width: 550,
    height: 330,
    xaxis_type: '',
    series_name: 'stage',
    x: 6.0,
    y: 14.0,
    w: 6.0,
    h: 17.6,
    i: 633,
    join_json: '{}',
    table_json: '',
    custom_function: '',
    custom_html: '0'
  }, {
    id: 700,
    category_id: 98,
    category_name: 'My',
    app_name: 'crm',
    report_type: 'table',
    page_type: 'dashboard',
    title: 'Top 5 Deals On Hand',
    title1: 'Top 5 Deals On Hand',
    tooltip: '',
    x_axis: '',
    y_axis: '',
    entity: 'top_deals',
    field: 'name,deal_value,created_date,user_id,stage\u0026l\u003d5',
    static_filter: '',
    width: 550,
    height: 330,
    xaxis_type: '',
    series_name: '',
    x: 0,
    y: 66.0,
    w: 16.0,
    h: 17.0,
    i: 700,
    join_json: '{}',
    table_json: '{ "table_data" : { "bulk" : true, "columns" : [ { "key" : "name", "label" : "Deal Name"}, { "key" : "deal_value", "label" : "Deal Value"}, { "key" : "created_date", "label" : "Created On"}, { "key" : "user_id", "label" : "Deal Owner"}, { "key" : "stage", "label" : "Stage"} ], "dropdown" : true, "option" : "options" } }',
    custom_function: '',
    custom_html: '0'
  }],
  filters: [{
    category_id: 98,
    category_name: 'My',
    column: 'created_date',
    type: 'calendar',
    url: 'https://www.google.com'
  }, {
    category_id: 99,
    category_name: 'Leads',
    column: 'created_date',
    type: 'calendar',
    url: 'https://www.google.com'
  }, {
    category_id: 100,
    category_name: 'Contacts',
    column: 'created_date',
    type: 'calendar',
    url: 'https://www.google.com'
  }, {
    category_id: 101,
    category_name: 'Companies',
    column: 'created_date',
    type: 'calendar',
    url: 'https://www.google.com'
  }, {
    category_id: 102,
    category_name: 'Deals',
    column: 'created_date',
    type: 'calendar',
    url: 'https://www.google.com'
  }, {
    category_id: 108,
    category_name: 'Deal Stages',
    column: 'created_date',
    type: 'calendar',
    url: 'https://www.google.com'
  }, {
    category_id: '108',
    category_name: 'Deal Stages',
    column: 'pipeline_id',
    type: 'dropdown',
    url: '/v2/pipelines?remove=true',
    option: [{
      value: 'all',
      label: 'Select Track',
      checked: 'true'
    }]
  }]

};
export default reportJson;
